services:
  mysql:
    image: mysql:latest
    container_name: erp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: erp-root-password
      MYSQL_USER: erp-user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: erp_wholesale_db
    ports:
      - "9001:3306"
    volumes:
      - erp-mysql-data:/var/lib/mysql
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: erp-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: erp-root-password
    ports:
      - "9000:80"
    depends_on:
      - mysql

  backend:
    build: .
    container_name: erp-backend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mysql
    environment:
      NODE_ENV: development
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: erp-user
      DB_PASSWORD: password
      DB_NAME: erp_wholesale_db
    command: ["npm", "run", "dev"]

volumes:
  erp-mysql-data:
